const LOG_MESSAGE = {
  REDIS_ON_SUCCESS: 'SUCCESS CONNECTION',
  REDIS_ON_ERROR:
    'FAILED TO CONNECT (MAKE SURE YOUR SERVER IS STARTED) OR TROUBLE SHOT THE FOLLOWING ERROR: ',
};

export { LOG_MESSAGE };
